### ISSUE TITLE
Please update chezmoi to version 1.8.3

### ISSUE THREAD

**Issue by twpayne** [rasmuskriest/Chocolatey-Packages#4]
Thanks for creating a chocolatey package for chezmoi!

Installing [chezmoi](https://github.com/twpayne/chezmoi) with `choco install chezmoi` installs version 1.8.1. The latest version of chezmoi is 1.8.3. Please could you update the chezmoi package to [version 1.8.3](https://github.com/twpayne/chezmoi/releases/tag/v1.8.3).

Refs https://github.com/twpayne/chezmoi/pull/759.

**Comment by rasmuskriest** [comment]
Thanks for your request. As per the PR's description, the package is being updated automatically. Both 1.8.2 and 1.8.3 are available in the repository, the update to the latter took place on June 26: https://chocolatey.org/packages/chezmoi/1.8.3

The reason they are not being installed when using `choco install chezmoi` is that the updated package appears to still be [in moderation](https://chocolatey.org/docs/chocolatey-faqs#what-is-moderation) since the first few versions have to be allowed manually (after a few versions without any problems, it should become a "trusted package"). It is possible to install the newer version(s) manually though: [How do I install a package version under moderation?](https://chocolatey.org/docs/chocolatey-faqs#how-do-i-install-a-package-version-under-moderation)

I am going to leave this issue open until the moderation of 1.8.3 has taken place and the updated package has been published succesfully.

**Comment by twpayne** [comment]
Ah, thank you for the explanation :)

**Comment by rasmuskriest** [comment]
1.8.3 has just been approved after 1.8.2 had been just a couple of days ago. Closing the issue.

**Comment by twpayne** [comment]
Brilliant, thank you very much :)
